backend:
  name: github
  repo: fahmolanrewaju-prog/fomwanbasicschool
  branch: main
  base_url: https://fomwan-cms-auth.fahmolanrewaju.workers.dev
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "News & Events"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}